[project]
name = "careos-api"
version = "0.1.0"
description = "CareOS API service"
requires-python = ">=3.12"
dependencies = [
  "Django==6.0.1",
]

[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"
